server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Importante para React Router: si la ruta no existe como archivo,
    # devolvemos index.html para que el router de React la maneje.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
